# Generated by Django 5.0 on 2024-01-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('task', models.CharField(max_length=400)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('university_name', models.CharField(max_length=200)),
            ],
        ),
    ]
