# Generated by Django 5.0 on 2024-01-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdrapp_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='university_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
