# Generated by Django 5.0 on 2024-01-02 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdrapp_1', '0004_alter_task_description_alter_task_task_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_on',
            field=models.DateField(blank=True, default='2023-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kdrapp_1.task'),
        ),
    ]
