# Generated by Django 5.0 on 2024-01-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kdrapp_1', '0005_alter_task_assigned_on_alter_user_details_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_on',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
    ]
