# Generated by Django 5.0 on 2024-01-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kdrapp_1', '0007_alter_user_details_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='join_date',
            field=models.DateField(null=True),
        ),
    ]
